[package]
name = "sqstransfer"
version = "0.1.0"
authors = ["ohke <kenta1988@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rusoto_core = "0.42.0"
rusoto_sqs = "0.42.0"
